# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 97dabd05d9e5d78c8fe6d4d46034c8e74f711811a3b486e8f4546438857bd1949d352f752028c3e31295513527b135ac81a90af3ee9f31a49a91b37430f5075a

test:
  secret_key_base: 8022d0cd32b0cfe02063b7e4561507e32f41f2cf0b3a18322b7d72564a7e6c67ee89ad642824dee897b90dcda490ffd4f79d08279cdf4bb0b1ca8855046c9822

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
